wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1659807535.48952
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      - 77
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      - 77
      3:
      - 23
      4: 3.9.13
      5: 0.13.0
      8:
      - 3
      - 5
